kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      name: demo
      labels:
        app: demo
        role: service
        env: dev
    spec:

      containers:

      - name: node
        image: chadmoon/demo:new
        imagePullPolicy: Always
        ports:
        - name: demo
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: demo
  selector:
    app: demo